# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Aerospike Node.js Linux Client Tests

on:
  push:
    branches:
      - master
      - maint/3.x
      - maint/4.x
      - gh-action
  pull_request:
    branches:
      - master
      - stage
      - maint/3.x
      - maint/4.x

jobs:
  build:
    runs-on: ubuntu-latest # https://github.com/actions/virtual-environments
    strategy:
      matrix:
        node-version: # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          - 16.x
          - 18.x
          - 19.x
          - 20.x
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - run: ./scripts/build-c-client.sh
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Set up Aerospike Database
      uses: reugn/github-action-aerospike@v1
    - run: npm install
    - run: npm run coverage
      env:
        AEROSPIKE_HOSTS: "127.0.0.1:3000"
        OPTIONS: "--timeout 30000"
    - run: npm run codecov
