# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Aerospike Node.js Windows Client Tests

on:
  push:
    branches:
      - master
      - maint/3.x
      - maint/4.x
      - gh-action
      - win-workflow-new
  pull_request:
    branches:
      - master
      - stage
      - maint/3.x
      - maint/4.x


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Aerospike Database
      uses: reugn/github-action-aerospike@v1

  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node: [ 10, 12, 14, 16 ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Update node-gyp
        run: |
          $WhereNode = Get-Command node | Select-Object -ExpandProperty Definition
          $NodeDirPath = Split-Path $WhereNode -Parent
          [Version]$npmVersion = npm --version
          if ($npmVersion -lt [Version]"7.0") {
            $NodeModulesPath = $NodeDirPath + "\node_modules\npm\node_modules\npm-lifecycle"
          } else {
            $NodeModulesPath = $NodeDirPath + "\node_modules\npm\node_modules\@npmcli\run-script"
          }
          cd $NodeModulesPath
          npm install node-gyp@8.x
      - run: npm install --unsafe-perm --build-from-source
        #      - run: npm test
